'use client';

import useOrderingService from '~/src/hooks/api/use-ordering-service';
import usePagination from '~/src/hooks/use-pagination';
import { useSearchParams } from 'next/navigation';
import { useEffect } from 'react';

const fakeData = {
   total_records: 7,
   total_pages: 2,
   page_size: 5,
   current_page: 1,
   items: [
      {
         tenant_id: null,
         branch_id: null,
         order_id: '073b0b68-f7fb-46a0-8851-1e472092f29c',
         customer_id: 'c3127b01-9101-4713-8e18-ae1f8f9ffd01',
         customer_email: 'user@gmail.com',
         order_code: '#912039',
         status: 'PAID',
         payment_method: 'VNPAY',
         shipping_address: {
            contact_name: 'Foo Bar',
            contact_email: 'user@gmail.com',
            contact_phone_number: '0333284890',
            contact_address_line: '123 Street',
            contact_district: 'Thu Duc',
            contact_province: 'Ho Chi Minh',
            contact_country: 'Vietnam',
         },
         order_items: [
            {
               order_item_id: '23e54d5b-02e5-4194-87dd-585007a22c4b',
               order_id: '073b0b68-f7fb-46a0-8851-1e472092f29c',
               tenant_id: null,
               branch_id: null,
               sku_id: null,
               model_id: '68e403d5617b27ad030bf28f',
               model_name: 'IPHONE_15',
               color_name: 'BLUE',
               storage_name: '128GB',
               unit_price: 1000.0,
               display_image_url:
                  'https://res.cloudinary.com/delkyrtji/image/upload/v1744960327/iphone-15-finish-select-202309-6-1inch-blue_zgxzmz.webp',
               model_slug: 'iphone-15',
               quantity: 1,
               is_reviewed: false,
               promotion_id: null,
               promotion_type: null,
               discount_type: null,
               discount_value: null,
               discount_amount: null,
               sub_total_amount: 1000.0,
               created_at: '2025-10-27T17:47:57.662349Z',
               updated_at: '2025-10-27T17:47:57.662349Z',
               updated_by: null,
               is_deleted: false,
               deleted_at: null,
               deleted_by: null,
            },
         ],
         promotion_id: null,
         promotion_type: null,
         discount_type: null,
         discount_value: null,
         discount_amount: null,
         total_amount: 1000,
         created_at: '2025-10-27T17:47:57.661369Z',
         updated_at: '2025-10-27T17:47:57.66137Z',
         updated_by: null,
         is_deleted: false,
         deleted_at: null,
         deleted_by: null,
      },
      {
         tenant_id: null,
         branch_id: null,
         order_id: '5b7404da-3b34-48f8-ab46-fc858b0698d7',
         customer_id: 'c3127b01-9101-4713-8e18-ae1f8f9ffd01',
         customer_email: 'user@gmail.com',
         order_code: '#268356',
         status: 'PAID',
         payment_method: 'VNPAY',
         shipping_address: {
            contact_name: 'Foo Bar',
            contact_email: 'user@gmail.com',
            contact_phone_number: '0333284890',
            contact_address_line: '123 Street',
            contact_district: 'Thu Duc',
            contact_province: 'Ho Chi Minh',
            contact_country: 'Vietnam',
         },
         order_items: [
            {
               order_item_id: '77cd2f63-5890-4fc5-8f85-ea86b0f4aef1',
               order_id: '5b7404da-3b34-48f8-ab46-fc858b0698d7',
               tenant_id: null,
               branch_id: null,
               sku_id: null,
               model_id: '68e403d5617b27ad030bf28f',
               model_name: 'IPHONE_15',
               color_name: 'BLUE',
               storage_name: '128GB',
               unit_price: 1000.0,
               display_image_url:
                  'https://res.cloudinary.com/delkyrtji/image/upload/v1744960327/iphone-15-finish-select-202309-6-1inch-blue_zgxzmz.webp',
               model_slug: 'iphone-15',
               quantity: 1,
               is_reviewed: false,
               promotion_id: '550e8400-e29b-41d4-a716-446655440000',
               promotion_type: 'COUPON',
               discount_type: 'PERCENTAGE',
               discount_value: 0.1,
               discount_amount: 100.0,
               sub_total_amount: 900.0,
               created_at: '2025-10-27T18:01:42.770772Z',
               updated_at: '2025-10-27T18:01:42.770772Z',
               updated_by: null,
               is_deleted: false,
               deleted_at: null,
               deleted_by: null,
            },
         ],
         promotion_id: '550e8400-e29b-41d4-a716-446655440000',
         promotion_type: 'COUPON',
         discount_type: 'PERCENTAGE',
         discount_value: 0.1,
         discount_amount: 100.0,
         total_amount: 900.0,
         created_at: '2025-10-27T18:01:42.769227Z',
         updated_at: '2025-10-27T18:01:42.769227Z',
         updated_by: null,
         is_deleted: false,
         deleted_at: null,
         deleted_by: null,
      },
      {
         tenant_id: null,
         branch_id: null,
         order_id: 'a6c9fbce-ab37-4472-b8d6-a3684b9d8241',
         customer_id: 'c3127b01-9101-4713-8e18-ae1f8f9ffd01',
         customer_email: 'user@gmail.com',
         order_code: '#750653',
         status: 'PAID',
         payment_method: 'VNPAY',
         shipping_address: {
            contact_name: 'Foo Bar',
            contact_email: 'user@gmail.com',
            contact_phone_number: '0333284890',
            contact_address_line: '123 Street',
            contact_district: 'Thu Duc',
            contact_province: 'Ho Chi Minh',
            contact_country: 'Vietnam',
         },
         order_items: [
            {
               order_item_id: '0c9d7078-2949-43e7-a4af-6acf3dd8453e',
               order_id: 'a6c9fbce-ab37-4472-b8d6-a3684b9d8241',
               tenant_id: null,
               branch_id: null,
               sku_id: null,
               model_id: 'ModelId',
               model_name: 'IPHONE_15',
               color_name: 'BLUE',
               storage_name: '256GB',
               unit_price: 1100.0,
               display_image_url:
                  'https://res.cloudinary.com/delkyrtji/image/upload/v1744960327/iphone-15-finish-select-202309-6-1inch-blue_zgxzmz.webp',
               model_slug: '',
               quantity: 1,
               is_reviewed: false,
               promotion_id: '99a356c8-c026-4137-8820-394763f30521',
               promotion_type: 'EVENT',
               discount_type: 'PERCENTAGE',
               discount_value: 0.1,
               discount_amount: 110.0,
               sub_total_amount: 990.0,
               created_at: '2025-10-27T18:07:03.60679Z',
               updated_at: '2025-10-27T18:07:03.60679Z',
               updated_by: null,
               is_deleted: false,
               deleted_at: null,
               deleted_by: null,
            },
         ],
         promotion_id: '99a356c8-c026-4137-8820-394763f30521',
         promotion_type: 'EVENT',
         discount_type: 'PERCENTAGE',
         discount_value: 0.1,
         discount_amount: 110.0,
         total_amount: 990.0,
         created_at: '2025-10-27T18:07:03.606782Z',
         updated_at: '2025-10-27T18:07:03.606782Z',
         updated_by: null,
         is_deleted: false,
         deleted_at: null,
         deleted_by: null,
      },
      {
         tenant_id: null,
         branch_id: null,
         order_id: 'd27b588e-5185-4f89-8739-204ec52009e6',
         customer_id: 'c3127b01-9101-4713-8e18-ae1f8f9ffd01',
         customer_email: 'user@gmail.com',
         order_code: '#989931',
         status: 'PAID',
         payment_method: 'VNPAY',
         shipping_address: {
            contact_name: 'Test',
            contact_email: 'user@gmail.com',
            contact_phone_number: 'Test',
            contact_address_line: 'Test',
            contact_district: 'Test',
            contact_province: 'Test',
            contact_country: 'Test',
         },
         order_items: [
            {
               order_item_id: '9dc6c733-07f3-4966-b5e0-79fe26d54813',
               order_id: 'd27b588e-5185-4f89-8739-204ec52009e6',
               tenant_id: null,
               branch_id: null,
               sku_id: null,
               model_id: '664351e90087aa09993f5ae7',
               model_name: 'IPHONE_15',
               color_name: 'PINK',
               storage_name: '128GB',
               unit_price: 1000.0,
               display_image_url:
                  'https://res.cloudinary.com/delkyrtji/image/upload/v1744960358/iphone-15-finish-select-202309-6-1inch-pink_j6v96t.webp',
               model_slug: '',
               quantity: 1,
               is_reviewed: false,
               promotion_id: null,
               promotion_type: null,
               discount_type: null,
               discount_value: null,
               discount_amount: null,
               sub_total_amount: 1000.0,
               created_at: '2025-10-28T15:57:04.337316Z',
               updated_at: '2025-10-28T15:57:04.337316Z',
               updated_by: null,
               is_deleted: false,
               deleted_at: null,
               deleted_by: null,
            },
         ],
         promotion_id: null,
         promotion_type: null,
         discount_type: null,
         discount_value: null,
         discount_amount: null,
         total_amount: 1000,
         created_at: '2025-10-28T15:57:04.337312Z',
         updated_at: '2025-10-28T15:57:04.337312Z',
         updated_by: null,
         is_deleted: false,
         deleted_at: null,
         deleted_by: null,
      },
      {
         tenant_id: null,
         branch_id: null,
         order_id: 'fde01a20-0c85-403f-8000-3fc279e60434',
         customer_id: 'c3127b01-9101-4713-8e18-ae1f8f9ffd01',
         customer_email: 'user@gmail.com',
         order_code: '#372909',
         status: 'CANCELLED',
         payment_method: 'COD',
         shipping_address: {
            contact_name: 'test',
            contact_email: 'user@gmail.com',
            contact_phone_number: 'test',
            contact_address_line: 'test',
            contact_district: 'test',
            contact_province: 'test',
            contact_country: 'test',
         },
         order_items: [
            {
               order_item_id: '958bde3a-758d-4e57-b66c-76a4b5379657',
               order_id: 'fde01a20-0c85-403f-8000-3fc279e60434',
               tenant_id: null,
               branch_id: null,
               sku_id: null,
               model_id: '664351e90087aa09993f5ae7',
               model_name: 'IPHONE_15',
               color_name: 'PINK',
               storage_name: '128GB',
               unit_price: 1000.0,
               display_image_url:
                  'https://res.cloudinary.com/delkyrtji/image/upload/v1744960358/iphone-15-finish-select-202309-6-1inch-pink_j6v96t.webp',
               model_slug: '',
               quantity: 1,
               is_reviewed: false,
               promotion_id: null,
               promotion_type: null,
               discount_type: null,
               discount_value: null,
               discount_amount: null,
               sub_total_amount: 1000.0,
               created_at: '2025-10-28T16:42:15.203427Z',
               updated_at: '2025-10-28T16:42:15.203427Z',
               updated_by: null,
               is_deleted: false,
               deleted_at: null,
               deleted_by: null,
            },
         ],
         promotion_id: null,
         promotion_type: null,
         discount_type: null,
         discount_value: null,
         discount_amount: null,
         total_amount: 1000,
         created_at: '2025-10-28T16:42:15.203422Z',
         updated_at: '2025-10-28T16:42:15.203422Z',
         updated_by: null,
         is_deleted: false,
         deleted_at: null,
         deleted_by: null,
      },
   ],
   links: {
      first: '?_page=1&_limit=5',
      prev: null,
      next: '?_page=2&_limit=5',
      last: '?_page=2&_limit=5',
   },
};

export type TOrder = typeof fakeData;
export type TOrderItem = (typeof fakeData.items)[number];

const OnlineOrdersPage = () => {
   const params = useSearchParams();

   console.log('params', params);

   const searchParams = Object.fromEntries(params.entries());

   console.log('searchParams', searchParams);

   const { getOrdersByAdminAsync, getOrdersByAdminState, isLoading } =
      useOrderingService();

   const {
      currentPage,
      totalPages,
      pageSize,
      totalRecords,
      isLastPage,
      isFirstPage,
      isNextPage,
      isPrevPage,
      paginationItems,
      getPageNumbers,
   } = usePagination(
      getOrdersByAdminState.data && getOrdersByAdminState.data.items.length > 0
         ? getOrdersByAdminState.data
         : {
              total_records: 0,
              total_pages: 0,
              page_size: 0,
              current_page: 0,
              items: [],
              links: {
                 first: null,
                 last: null,
                 prev: null,
                 next: null,
              },
           },
   );

   useEffect(() => {
      const fetchOrders = async () => {
         await getOrdersByAdminAsync(searchParams);
      };
      fetchOrders();
   }, [getOrdersByAdminAsync]);

   return (
      <div>
         <h1>Online Orders</h1>
      </div>
   );
};

export default OnlineOrdersPage;
