const images = {
     ip14ProMax: '/images/compare-imgs/iphones/ip14-pro-max.png',
     ip14Plus: '/images/compare-imgs/iphones/ip14-plus.png',
     ip13ProMax: '/images/compare-imgs/iphones/ip13-pro-max.png',
     ip13Mini: '/images/compare-imgs/iphones/ip13-mini.png',
     ip12Mini: '/images/compare-imgs/iphones/ip12-mini.png',
     ip16ProMaxMasonry1:'/images/detail-imgs/ip16-pro-max/iphone-16-pro-model-unselect-gallery-1.png',
     ip16ProMaxMasonry2:'/images/detail-imgs/ip16-pro-max/iphone-16-pro-model-unselect-gallery-2.png',
     ip16ProWhiteTitaniumSelect:'/images/detail-imgs/ip16-pro-max/iphone-16-pro-whitetitanium-select.jpg',
     ip16ProWhiteTitaniumWitb:'/images/detail-imgs/ip16-pro-max/iphone-16-pro-whitetitanium-witb.jpg',
     ip16ProBraidedCable:'/images/detail-imgs/ip16-pro-max/iphone-16-pro-braided-cable-witb.jpg',
     ipXSMax: '/images/compare-imgs/iphones/ipXS-max.png',
     icAtt:'/images/carrier-imgs/banner-att.png',
     icTmobile:'/images/carrier-imgs/banner-tmobile.png',
     icVerizon:'/images/carrier-imgs/banner-verizon.png',
     icLightYear:'/images/carrier-imgs/banner-lightyear.png',
     logoAtt:'/images/carrier-imgs/logo-att.png',
     logoTmobile:'/images/carrier-imgs/logo-tmobile.png',
     logoVerizon:'/images/carrier-imgs/logo-verizon.png',
     logoLightYear:'/images/carrier-imgs/logo-lightyear.png',
     helpAppleCare:'/images/help-imgs/help-applecare.jpg',
     helpStorage:'/images/help-imgs/help-storage.jpg',
     helpTradeInPrePurchase:'/images/help-imgs/help-trade-in-pre-purchase.jpg',
     serviceArcade:'/images/service-imgs/iphone-services-arcade.png',
     serviceFitness:'/images/service-imgs/iphone-services-fitness.png',
     serviceNews:'/images/service-imgs/iphone-services-news.png',
     serviceTV:'/images/service-imgs/iphone-services-tv.png',
};
  
export default images;