version: "3.4"

services:
  seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
