services:
    db.catalog.replica.primary:
        container_name: db.catalog.replica.primary
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_REPLICASET=rs0
            - MONGO_HOST_IP=192.168.0.4
        ports:
            - 27001:27017
        volumes:
            - ./provision/dockerVolumes/mongoDb/volumes/replica-primary:/data/db
            - ./provision/dockerVolumes/mongoDb/scripts/rs_config.sh:/docker-entrypoint-initdb.d/rs_config.sh:ro
            # - ./provision/dockerVolumes/mongoDb/key/replica.key:/key/replica.key
        command: mongod --replSet "rs0" --bind_ip_all --replSetName rs0
        user: "999:999"
        networks:
            - app-network

    db.catalog.replica.secondary:
        container_name: db.catalog.replica.secondary
        image: mongo:latest
        restart: always
        ports:
            - 27002:27017
        environment:
            - MONGO_INITDB_REPLICASET=rs0
        volumes:
            - ./provision/dockerVolumes/mongoDb/volumes/replica-secondary:/data/db
            # - ./provision/dockerVolumes/mongoDb/key/replica.key:/key/replica.key
        command: mongod --replSet "rs0" --bind_ip_all --replSetName rs0
        user: "999:999"
        networks:
            - app-network

    db.catalog.replica.arbiter:
        container_name: db.catalog.replica.arbiter
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_REPLICASET=rs0
        ports:
            - 27003:27017
        volumes:
            - ./provision/dockerVolumes/mongoDb/volumes/replica-arbiter:/data/db
            # - ./provision/dockerVolumes/mongoDb/key/replica.key:/key/replica.key
        command: mongod --replSet "rs0" --bind_ip_all --replSetName rs0
        user: "999:999"
        networks:
            - app-network

    mongo-init:
        container_name: mongo-replica-init
        image: mongo:latest
        depends_on:
            - db.catalog.replica.primary
            - db.catalog.replica.secondary
            - db.catalog.replica.arbiter
        environment:
            - MONGO_HOST_IP=192.168.0.4
        volumes:
            - ./provision/dockerVolumes/mongoDb/scripts/rs_config.sh:/scripts/rs_config.sh
        command: >
            bash -c "
            chmod +x /scripts/rs_config.sh &&
            sleep 10 &&
            /scripts/rs_config.sh
            "
        networks:
            - app-network
        restart: "no"

networks:
    app-network:
        name: app-network
        driver: bridge
