services:
  db.keycloak:
    image: postgres:alpine

  db.identity:
    image: postgres:alpine

  db.catalog:
    image: mongo:latest

  db.basket:
    image: postgres:alpine

  db.discount:
    image: postgres:alpine

  db.ordering:
    image: postgres:alpine

  # db.distributedcache:
  #   image: redis:alpine

  # mq.rabbitmq:
  #   image: rabbitmq:management

  ygz.keycloak.api:
    image: ${DOCKER_REGISTRY-}ygzkeycloakapi
    build:
      context: .
      dockerfile: Services/Identity/YGZ.Keycloak.Api/Dockerfile

  ygz.catalog.api:
    image: ${DOCKER_REGISTRY-}ygzcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/YGZ.Catalog.Api/Dockerfile

  ygz.basket.api:
    image: ${DOCKER_REGISTRY-}ygzbasketapi
    build:
      context: .
      dockerfile: Services/Basket/YGZ.Basket.Api/Dockerfile

  ygz.discount.grpc:
    image: ${DOCKER_REGISTRY-}ygzdiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/YGZ.Discount.Grpc/Dockerfile

  ygz.gateways.yarp:
    image: ${DOCKER_REGISTRY-}ygzgatewaysyarp
    build:
      context: .
      dockerfile: Gateways/YGZ.Gateways.Yarp/Dockerfile

  ygz.ordering.api:
    image: ${DOCKER_REGISTRY-}ygzorderingapi
    build:
      context: .
      dockerfile: Services/Ordering/YGZ.Ordering.Api/Dockerfile

  ygz.seq:
    image: datalust/seq
  
  ygz.keycloak.server:
    image: quay.io/keycloak/keycloak:latest

  ygz.jaeger.opentelemetry:
    image: jaegertracing/all-in-one:latest

