services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: bale
      POSTGRES_PASSWORD: bale
      POSTGRES_DB: postgresDb
    restart: always
    ports:
      - "6432:5432"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: bale
      MONGO_INITDB_ROOT_PASSWORD: bale
    restart: always
    ports:
      - "27017:27017"
