services:
  db.identity:
    image: postgres:alpine

  # catalogdb:
  #   image: mongo:latest

  # basketdb:
  #   image: postgres:alpine

  # discountdb:
  #   image: postgres:alpine

  # orderingdb:
  #   image: postgres:alpine

  # distributedcache:
  #   image: redis:alpine

  # messagebroker:
  #   image: rabbitmq:management

  ygz.gateways.yarp:
    image: ${DOCKER_REGISTRY-}ygzgatewaysyarp
    build:
      context: .
      dockerfile: Gateways/YGZ.Gateways.Yarp/Dockerfile

  ygz.identity.api:
    image: ${DOCKER_REGISTRY-}ybeidentityapi
    build:
      context: .
      dockerfile: Services/Identity/YGZ.Identity.Api/Dockerfile
  
  ygz.keycloak.api:
    image: ${DOCKER_REGISTRY-}ygzkeycloakapi
    build:
      context: .
      dockerfile: Services/Identity/YGZ.Keycloak.Api/Dockerfile


  # ygz.catalog.api:
  #   image: ${DOCKER_REGISTRY-}ygzcatalogapi
  #   build:
  #     context: .
  #     dockerfile: Services/Catalog/YGZ.Catalog.Api/Dockerfile

  # ygz.basket.api:
  #   image: ${DOCKER_REGISTRY-}ygzbasketapi
  #   build:
  #     context: .
  #     dockerfile: Services/Basket/YGZ.Basket.Api/Dockerfile

  # gyz.discount.grpc:
  #   image: ${DOCKER_REGISTRY-}gyzdiscountgrpc
  #   build:
  #     context: .
  #     dockerfile: Services/Discount/GYZ.Discount.Grpc/Dockerfile

  # ygz.ordering.api:
  #   image: ${DOCKER_REGISTRY-}ygzorderingapi
  #   build:
  #     context: .
  #     dockerfile: Services/Ordering/YGZ.Ordering.Api/Dockerfile

  # ygz.seq:
  #   image: datalust/seq
  
  ygz.keycloak.server:
    image: quay.io/keycloak/keycloak:latest

  ygz.jaeger.opentelemetry:
    image: jaegertracing/all-in-one:latest

volumes:
  postgres_identity:
  # postgres_basket:
  # postgres_discount:
  # mongodb_catalog:

