services:
  ygz.gateway.api:
    # image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: ./Gateways/Gateway.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - backendbridge

  # ygz.identity.api:
  #   # image: ${DOCKER_REGISTRY-}ybeidentityapi
  #   build:
  #     context: .
  #     dockerfile: Services/Identity/YGZ.Identity.Api/Dockerfile
  #   ports:
  #     - "5000:5000"

  identitytest1:
    # image: ${DOCKER_REGISTRY-}identitytest1
    build:
      context: .\Services\IdentityTest\IdentityTest1
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
      - "5051:8081"
    networks:
      - backendbridge

  identitytest2:
    # image: ${DOCKER_REGISTRY-}identitytest2
    build:
      context: .\Services\IdentityTest\IdentityTest2
      dockerfile: Dockerfile
    ports:
      - "6060:8080"
      - "6061:8081"
    networks:
      - backendbridge

networks:
  backendbridge:
    name: backendbridge
    driver: bridge
