-- public."Roles" definition
CREATE TABLE public."Roles" (
	"Id" text NOT NULL,
	"Name" varchar(256) NULL,
	"NormalizedName" varchar(256) NULL,
	"ConcurrencyStamp" text NULL,
	CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "RoleNameIndex" ON public."Roles" USING btree ("NormalizedName");


-- public."Users" definition
CREATE TABLE public."Users" (
	"Id" text NOT NULL,
	"UserName" varchar(256) NULL,
	"NormalizedUserName" varchar(256) NULL,
	"Email" varchar(256) NULL,
	"NormalizedEmail" varchar(256) NULL,
	"EmailConfirmed" bool NOT NULL,
	"PasswordHash" text NULL,
	"SecurityStamp" text NULL,
	"ConcurrencyStamp" text NULL,
	"PhoneNumber" text NULL,
	"PhoneNumberConfirmed" bool NOT NULL,
	"TwoFactorEnabled" bool NOT NULL,
	"LockoutEnd" timestamptz NULL,
	"LockoutEnabled" bool NOT NULL,
	"AccessFailedCount" int4 NOT NULL,
	CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);
CREATE INDEX "EmailIndex" ON public."Users" USING btree ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON public."Users" USING btree ("NormalizedUserName");


-- public."Profiles" definition
CREATE TABLE public."Profiles" (
	"Id" uuid NOT NULL,
	"FirstName" text NOT NULL,
	"LastName" text NOT NULL,
	"BirthDay" timestamptz NOT NULL,
	"Gender" text NOT NULL,
	"ImageId" text DEFAULT ''::text NULL,
	"ImageUrl" text DEFAULT ''::text NULL,
	"UserId" text NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
	CONSTRAINT "PK_Profiles" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Profiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX "IX_Profiles_UserId" ON public."Profiles" USING btree ("UserId");


-- public."RoleClaims" definition
CREATE TABLE public."RoleClaims" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"RoleId" text NOT NULL,
	"ClaimType" text NULL,
	"ClaimValue" text NULL,
	CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_RoleClaims_RoleId" ON public."RoleClaims" USING btree ("RoleId");


-- public."ShippingAddresses" definition
CREATE TABLE public."ShippingAddresses" (
	"Id" uuid NOT NULL,
	"Label" text NOT NULL,
	"ContactName" text NOT NULL,
	"ContactPhoneNumber" text NOT NULL,
	"AddressLine" text NOT NULL,
	"AddressDistrict" text NOT NULL,
	"AddressProvince" text NOT NULL,
	"AddressCountry" text NOT NULL,
	"IsDefault" bool NOT NULL,
	"UserId" text NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
	CONSTRAINT "PK_ShippingAddresses" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_ShippingAddresses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_ShippingAddresses_UserId" ON public."ShippingAddresses" USING btree ("UserId");


-- public."UserClaims" definition
CREATE TABLE public."UserClaims" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"UserId" text NOT NULL,
	"ClaimType" text NULL,
	"ClaimValue" text NULL,
	CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_UserClaims_UserId" ON public."UserClaims" USING btree ("UserId");


-- public."UserLogins" definition
CREATE TABLE public."UserLogins" (
	"LoginProvider" text NOT NULL,
	"ProviderKey" text NOT NULL,
	"ProviderDisplayName" text NULL,
	"UserId" text NOT NULL,
	CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
	CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_UserLogins_UserId" ON public."UserLogins" USING btree ("UserId");


-- public."UserRoles" definition
CREATE TABLE public."UserRoles" (
	"UserId" text NOT NULL,
	"RoleId" text NOT NULL,
	CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
	CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles"("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_UserRoles_RoleId" ON public."UserRoles" USING btree ("RoleId");


-- public."UserTokens" definition
CREATE TABLE public."UserTokens" (
	"UserId" text NOT NULL,
	"LoginProvider" text NOT NULL,
	"Name" text NOT NULL,
	"Value" text NULL,
	CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
	CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE
);