// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YGZ.Ordering.Infrastructure.Persistence;

#nullable disable

namespace YGZ.Ordering.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YGZ.Ordering.Application.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PaymentMethod");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("Status");

                    b.Property<decimal>("SubTotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Code", "YGZ.Ordering.Application.Orders.Order.Code#Code", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Code");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ShippingAddress", "YGZ.Ordering.Application.Orders.Order.ShippingAddress#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ShippingAddressAddressLine");

                            b1.Property<string>("ContactEmail")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ShippingAddressContactEmail");

                            b1.Property<string>("ContactName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ShippingAddressContactName");

                            b1.Property<string>("ContactPhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ShippingAddressContactPhoneNumber");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ShippingAddressCountry");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ShippingAddressDistrict");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ShippingAddressProvince");
                        });

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YGZ.Ordering.Domain.Orders.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductColorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProductUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("YGZ.Ordering.Domain.Orders.Entities.OrderItem", b =>
                {
                    b.HasOne("YGZ.Ordering.Application.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("YGZ.Ordering.Domain.Orders.ValueObjects.Promotion", "Promotion", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("PromotionAppliedProductCount")
                                .HasColumnType("integer")
                                .HasColumnName("PromotionAppliedProductCount");

                            b1.Property<string>("PromotionDiscountType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PromotionDiscountType");

                            b1.Property<decimal>("PromotionDiscountUnitPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("PromotionDiscountUnitPrice");

                            b1.Property<decimal>("PromotionDiscountValue")
                                .HasColumnType("numeric")
                                .HasColumnName("PromotionDiscountValue");

                            b1.Property<string>("PromotionEventType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PromotionEventType");

                            b1.Property<decimal>("PromotionFinalPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("PromotionFinalPrice");

                            b1.Property<string>("PromotionIdOrCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PromotionIdOrCode");

                            b1.Property<string>("PromotionTitle")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PromotionTitle");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("Order");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("YGZ.Ordering.Application.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
