@startuml
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false
skinparam defaultFontName Arial
skinparam usecase {
    BackgroundColor #F8F8F8
    BorderColor #666666
    ArrowColor #444444
}

actor "Staff" as staff #orange
actor "Admin" as admin #salmon

package "STAFF & ADMIN role & Admin App" {
    usecase (UC32: View dashboard) as UC32
    usecase (UC33: Filter revenue) as UC33

    usecase (UC41: View events) as UC41
    usecase (UC43: View event details) as UC43

    usecase (UC45: View categories) as UC45
    usecase (UC47: View category details) as UC47

    usecase (UC49: View staffs) as UC49
    usecase (UC50: Filter staff) as UC50
    usecase (UC51: Add staff) as UC51
    usecase (UC52: View staff details) as UC52
    usecase (UC53: Update staff) as UC53

    usecase (UC54: View products) as UC54
    usecase (UC55: Filter product) as UC55
    usecase (UC57: View product details) as UC57

    usecase (UC59: View inventory) as UC59
    usecase (UC60: Filter sku) as UC60

    usecase (UC61: View customers) as UC61
    usecase (UC62: Filter customer) as UC62
    usecase (UC63: View customer details) as UC63

    usecase (UC64: View orders) as UC64
    usecase (UC65: Filter order) as UC65
    usecase (UC66: View order details) as UC66
}

'=== Extends (<<extend>>) ===
UC32 <.. UC33 : <<extend>>

UC41 <.. UC43 : <<extend>>

UC45 <.. UC47 : <<extend>>

UC49 <.. UC50 : <<extend>>
UC49 <.. UC51 : <<extend>>
UC49 <.. UC52 : <<extend>>
UC52 <.. UC53 : <<extend>>
UC54 <.. UC55 : <<extend>>
UC54 <.. UC57 : <<extend>>

UC59 <.. UC60 : <<extend>>
UC61 <.. UC62 : <<extend>>
UC61 <.. UC63 : <<extend>>
UC64 <.. UC65 : <<extend>>
UC64 <.. UC66 : <<extend>>


staff <|-- admin

staff --> UC41
staff --> UC45
staff --> UC54
staff --> UC59
staff --> UC61
staff --> UC64

admin --> UC32
admin --> UC49
