import type { Metadata } from 'next';
import '~/globals.css';
import {
   fontMono,
   fontSans,
   SFDisplayFont,
   SFTextFont,
} from '~/assets/fonts/font.config';
import { cn } from '~/src/infrastructure/lib/utils';
import { ReduxProvider } from '~/src/infrastructure/redux/provider';
import { ThemeProvider } from '@components/ui/theme-provider';
import { Toaster } from '@components/ui/toaster';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body
            className={cn(
               'antialiased',
               fontSans.variable,
               fontMono.variable,
               SFDisplayFont.variable,
               SFTextFont.variable,
            )}
         >
            <ReduxProvider>
               <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
               >
                  <main>
                     <Toaster />
                     {children}
                  </main>
               </ThemeProvider>
            </ReduxProvider>
         </body>
      </html>
   );
}
