import type { Metadata } from "next";
import "~/styles/globals.css";
import { fontMono, fontSans } from "~/fonts";
import { ThemeProvider } from "~/components/theme-provider";

export const metadata: Metadata = {
  title: "ygzStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
