// <auto-generated />
using System;
using GYZ.Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GYZ.Discount.Grpc.Data.Migrations
{
    [DbContext(typeof(DiscountDbContext))]
    partial class DiscountDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GYZ.Discount.Grpc.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DiscountValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxDiscountAmount")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinPurchaseAmount")
                        .HasColumnType("double precision");

                    b.Property<int>("QuantityRemain")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d203cbdc-f010-4ec6-9d42-512893ca7006"),
                            Code = "CODE",
                            CreatedAt = new DateTime(2024, 12, 3, 7, 33, 39, 449, DateTimeKind.Utc).AddTicks(2328),
                            Description = "Summer 2024 description",
                            DiscountValue = 0.20000000000000001,
                            QuantityRemain = 20,
                            Status = 1,
                            Title = "Summer 2024",
                            Type = 0,
                            UpdatedAt = new DateTime(2024, 12, 3, 7, 33, 39, 449, DateTimeKind.Utc).AddTicks(2329),
                            UsageLimit = 20,
                            ValidFrom = new DateTime(2024, 12, 3, 7, 33, 39, 448, DateTimeKind.Utc).AddTicks(9761),
                            ValidTo = new DateTime(2024, 12, 3, 7, 33, 39, 449, DateTimeKind.Utc).AddTicks(543)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
