export const categoryList = [
   {
      id: '1',
      name: 'Store',
      description: 'Store description',
      navigate: '/store',
      order: 0,
      parent_id: null,
   },
   {
      id: '2',
      name: 'Mac',
      description: 'Mac description',
      navigate: '/mac',
      order: 0,
      parent_id: null,
   },
   {
      id: '3',
      name: 'iPad',
      description: 'iPad description',
      navigate: '/ipad',
      order: 0,
      parent_id: null,
   },
   {
      id: '4',
      name: 'iPhone',
      description: 'iPhone description',
      navigate: '/iphone',
      order: 0,
      parent_id: null,
   },
   {
      id: '5',
      name: 'Watch',
      description: 'Watch description',
      navigate: '/watch',
      order: 0,
      parent_id: null,
   },
   {
      id: '6',
      name: 'HeadPhones',
      description: 'HeadPhones description',
      navigate: '/headphones',
      order: 0,
      parent_id: null,
   },
   {
      id: '7',
      name: 'Vision',
      description: 'Vision Pro description',
      navigate: '/vision-pro',
      order: 0,
      parent_id: null,
   },
   {
      id: '8',
      name: 'TV & Home',
      description: 'TV & Home description',
      navigate: '/tv-home',
      order: 0,
      parent_id: null,
   },
   {
      id: '9',
      name: 'Entertainment',
      description: 'Entertainment description',
      navigate: '/entertainment',
      order: 0,
      parent_id: null,
   },
   {
      id: '10',
      name: 'Accessories',
      description: 'Accessories description',
      navigate: '/accessories',
      order: 0,
      parent_id: null,
   },
   {
      id: '11',
      name: 'Support',
      description: 'Support description',
      navigate: '/support',
      order: 0,
      parent_id: null,
   },
];
