export const countries = [
   //  'Afghanistan',
   //  'Albania',
   //  'Algeria',
   //  'Andorra',
   //  'Angola',
   //  'Argentina',
   //  'Armenia',
   //  'Australia',
   //  'Austria',
   //  'Belgium',
   //  'Brazil',
   //  'Canada',
   //  'China',
   //  'Denmark',
   //  'Egypt',
   //  'Finland',
   //  'France',
   //  'Germany',
   //  'Greece',
   //  'India',
   //  'Indonesia',
   //  'Iran',
   //  'Iraq',
   //  'Ireland',
   //  'Israel',
   //  'Italy',
   //  'Japan',
   //  'Kenya',
   //  'Korea, South',
   //  'Mexico',
   //  'Netherlands',
   //  'New Zealand',
   //  'Norway',
   //  'Pakistan',
   //  'Poland',
   //  'Portugal',
   //  'Russia',
   //  'Saudi Arabia',
   //  'Singapore',
   //  'South Africa',
   //  'Spain',
   //  'Sweden',
   //  'Switzerland',
   //  'Taiwan',
   //  'Tajikistan',
   //  'Tanzania',
   //  'Thailand',
   //  'Timor-Leste',
   //  'Togo',
   //  'Tokelau',
   //  'Tonga',
   //  'Trinidad and Tobago',
   //  'Tunisia',
   //  'Türkiye',
   //  'Turkmenistan',
   //  'Turks and Caicos Islands',
   //  'Tuvalu',
   //  'Uganda',
   //  'Ukraine',
   //  'United Arab Emirates',
   'United Kingdom',
   'United States',
   'Việt Nam',
];
