namespace YGZ.BuildingBlocks.Shared.Constants;

public static class CountryConstants
{
    public static readonly IReadOnlyList<string> Countries =
    [
        // "Afghanistan",
        // "Albania",
        // "Algeria",
        // "Andorra",
        // "Angola",
        // "Argentina",
        // "Armenia",
        // "Australia",
        // "Austria",
        // "Belgium",
        // "Brazil",
        // "Canada",
        // "China",
        // "Denmark",
        // "Egypt",
        // "Finland",
        // "France",
        // "Germany",
        // "Greece",
        // "India",
        // "Indonesia",
        // "Iran",
        // "Iraq",
        // "Ireland",
        // "Israel",
        // "Italy",
        // "Japan",
        // "Kenya",
        // "Korea, South",
        // "Malaysia",
        // "Mexico",
        // "Netherlands",
        // "New Zealand",
        // "Norway",
        // "Pakistan",
        // "Philippines",
        // "Poland",
        // "Portugal",
        // "Russia",
        // "Saudi Arabia",
        // "Singapore",
        // "South Africa",
        // "Spain",
        // "Sweden",
        // "Switzerland",
        // "Taiwan",
        // "Tajikistan",
        // "Tanzania",
        // "Thailand",
        // "Timor-Leste",
        // "Togo",
        // "Tokelau",
        // "Tonga",
        // "Trinidad and Tobago",
        // "Tunisia",
        // "Turkiye",
        // "Turkmenistan",
        // "Turks and Caicos Islands",
        // "Tuvalu",
        // "Uganda",
        // "Ukraine",
        // "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Việt Nam"
    ];
}
