export const environments = {
   IDENTITY_PROVIDER_LOGIN_REDIRECT_URL:
      process.env.IDENTITY_PROVIDER_LOGIN_REDIRECT_URL,
   IDENTITY_PROVIDER_CLIENT_ID: process.env.IDENTITY_PROVIDER_CLIENT_ID,
   IDENTITY_PROVIDER_CLIENT_SECRET: process.env.IDENTITY_PROVIDER_CLIENT_SECRET,
   IDENTITY_PROVIDER_REDIRECT_URL: process.env.IDENTITY_PROVIDER_REDIRECT_URL,
   IDENTITY_PROVIDER_TOKEN_URL: process.env.IDENTITY_PROVIDER_TOKEN_URL,
   IDENTITY_PROVIDER_ISSUER: process.env.IDENTITY_PROVIDER_ISSUER,
   NEXTAUTH_URL: process.env.NEXTAUTH_URL,
   NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
};
