export enum PROMOTION_EVENT_TYPE_ENUM {
   'PROMOTION_UNKNOWN' = 'PROMOTION_UNKNOWN',
   'PROMOTION_COUPON' = 'PROMOTION_COUPON',
   'PROMOTION_ITEM' = 'PROMOTION_ITEM',
   'PROMOTION_EVENT' = 'PROMOTION_EVENT',
}

export enum DISCOUNT_TYPE_ENUM {
   'UNKNOWN' = 'UNKNOWN',
   'PERCENTAGE' = 'PERCENTAGE',
   'FIXED' = 'FIXED',
}
