export enum ORDER_STATUS_TYPE_ENUM {
   'PENDING' = 'PENDING',
   'CONFIRMED' = 'CONFIRMED',
   'PREPARING' = 'PREPARING',
   'DELIVERING' = 'DELIVERING',
   'CANCELLED' = 'CANCELLED',
   'PAID' = 'PAID',
   'DELIVERED' = 'DELIVERED',
}
