export enum EOrderStatus {
   PENDING = 'PENDING',
   CONFIRMED = 'CONFIRMED',
   PREPARING = 'PREPARING',
   DELIVERING = 'DELIVERING',
   CANCELLED = 'CANCELLED',
   PAID = 'PAID',
   DELIVERED = 'DELIVERED',
   PENDING_ASSIGNMENT = 'PENDING_ASSIGNMENT',
}
