#! /bin/bash
dotnet ef migrations add "InitialMigrationReview" \
--startup-project ../../Services/Ordering/YGZ.Ordering.Api \
--project ../../Services/Ordering/YGZ.Ordering.Infrastructure \
--output-dir Persistence/Migrations