/* eslint-disable react/react-in-jsx-scope */
import type { Metadata } from 'next';
import '/globals.css';
import { SFDisplayFont, SFTextFont } from '@assets/fonts/font.config';
import { cn } from '~/infrastructure/lib/utils';
import { ReduxProvider } from '~/infrastructure/redux/provider';
import Header from '~/components/Header';
import Footer from '~/components/Footer';

export const metadata: Metadata = {
   description: 'Generated by create next app',
   title: 'Create Next App',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={cn(
               'antialiased',
               SFDisplayFont.variable,
               SFTextFont.variable,
               'font-SFProDisplay',
            )}
         >
            <main>
               <ReduxProvider>
                  <Header />
                  {children}
                  <Footer />
               </ReduxProvider>
            </main>
         </body>
      </html>
   );
}
