export const iphoneFakeData = {
   total_records: 1,
   total_pages: 1,
   page_size: 1,
   current_page: 1,
   items: [
      {
         id: '68e80ce7e424d0f8cd8a35d0',
         category: {
            id: '68e3fc0c240062be872a0379',
            name: 'iPhone',
            description: 'iPhone categories.',
            order: 0,
            slug: 'iphone',
            parent_id: null,
            created_at: '2025-10-10T21:23:02.958799+07:00',
            updated_at: '2025-10-10T21:23:02.9588779+07:00',
            modified_by: null,
            is_deleted: false,
            deleted_at: null,
            deleted_by: null,
         },
         name: 'iPhone 15',
         model_items: [
            {
               name: 'iPhone 15',
               normalized_name: 'IPHONE_15',
               order: 0,
            },
            {
               name: 'iPhone 15 Plus',
               normalized_name: 'IPHONE_15_PLUS',
               order: 1,
            },
         ],
         color_items: [
            {
               name: 'Blue',
               normalized_name: 'BLUE',
               hex_code: '#D5DDDF',
               showcase_image_id:
                  'iphone-15-finish-select-202309-6-1inch-blue_zgxzmz',
               order: 0,
            },
            {
               name: 'Pink',
               normalized_name: 'PINK',
               hex_code: '#EBD3D4',
               showcase_image_id:
                  'iphone-15-finish-select-202309-6-1inch-pink_j6v96t',
               order: 1,
            },
            {
               name: 'Yellow',
               normalized_name: 'YELLOW',
               hex_code: '#EDE6C8',
               showcase_image_id:
                  'iphone-15-finish-select-202309-6-1inch-yellow_pwviwe',
               order: 2,
            },
            {
               name: 'Green',
               normalized_name: 'GREEN',
               hex_code: '#D0D9CA',
               showcase_image_id:
                  'iphone-15-finish-select-202309-6-1inch-green_yk0ln5',
               order: 3,
            },
            {
               name: 'Black',
               normalized_name: 'BLACK',
               hex_code: '#4B4F50',
               showcase_image_id:
                  'iphone-15-finish-select-202309-6-1inch-black_hhhvfs',
               order: 4,
            },
         ],
         storage_items: [
            {
               name: '128GB',
               normalized_name: '128GB',
               order: 0,
            },
            {
               name: '256GB',
               normalized_name: '256GB',
               order: 1,
            },
            {
               name: '512GB',
               normalized_name: '512GB',
               order: 2,
            },
            {
               name: '1TB',
               normalized_name: '1TB',
               order: 3,
            },
         ],
         sku_prices: [
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'BLUE',
               normalized_storage: '128GB',
               unit_price: 1000,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'BLUE',
               normalized_storage: '256GB',
               unit_price: 1100,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'BLUE',
               normalized_storage: '512GB',
               unit_price: 1200,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'BLUE',
               normalized_storage: '1TB',
               unit_price: 1300,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'PINK',
               normalized_storage: '128GB',
               unit_price: 1000,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'PINK',
               normalized_storage: '256GB',
               unit_price: 1100,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'PINK',
               normalized_storage: '512GB',
               unit_price: 1200,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'PINK',
               normalized_storage: '1TB',
               unit_price: 1300,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'YELLOW',
               normalized_storage: '128GB',
               unit_price: 1000,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'YELLOW',
               normalized_storage: '256GB',
               unit_price: 1100,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'YELLOW',
               normalized_storage: '512GB',
               unit_price: 1200,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'YELLOW',
               normalized_storage: '1TB',
               unit_price: 1300,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'GREEN',
               normalized_storage: '128GB',
               unit_price: 1000,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'GREEN',
               normalized_storage: '256GB',
               unit_price: 1100,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'GREEN',
               normalized_storage: '512GB',
               unit_price: 1200,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'GREEN',
               normalized_storage: '1TB',
               unit_price: 1300,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'BLACK',
               normalized_storage: '128GB',
               unit_price: 1000,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'BLACK',
               normalized_storage: '256GB',
               unit_price: 1100,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'BLACK',
               normalized_storage: '512GB',
               unit_price: 1200,
            },
            {
               normalized_model: 'IPHONE_15',
               normalized_color: 'BLACK',
               normalized_storage: '1TB',
               unit_price: 1300,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'BLUE',
               normalized_storage: '128GB',
               unit_price: 1000,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'BLUE',
               normalized_storage: '256GB',
               unit_price: 1100,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'BLUE',
               normalized_storage: '512GB',
               unit_price: 1200,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'BLUE',
               normalized_storage: '1TB',
               unit_price: 1300,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'PINK',
               normalized_storage: '128GB',
               unit_price: 1000,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'PINK',
               normalized_storage: '256GB',
               unit_price: 1100,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'PINK',
               normalized_storage: '512GB',
               unit_price: 1200,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'PINK',
               normalized_storage: '1TB',
               unit_price: 1300,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'YELLOW',
               normalized_storage: '128GB',
               unit_price: 1000,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'YELLOW',
               normalized_storage: '256GB',
               unit_price: 1100,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'YELLOW',
               normalized_storage: '512GB',
               unit_price: 1200,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'YELLOW',
               normalized_storage: '1TB',
               unit_price: 1300,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'GREEN',
               normalized_storage: '128GB',
               unit_price: 1000,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'GREEN',
               normalized_storage: '256GB',
               unit_price: 1100,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'GREEN',
               normalized_storage: '512GB',
               unit_price: 1200,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'GREEN',
               normalized_storage: '1TB',
               unit_price: 1300,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'BLACK',
               normalized_storage: '128GB',
               unit_price: 1000,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'BLACK',
               normalized_storage: '256GB',
               unit_price: 1100,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'BLACK',
               normalized_storage: '512GB',
               unit_price: 1200,
            },
            {
               normalized_model: 'IPHONE_15_PLUS',
               normalized_color: 'BLACK',
               normalized_storage: '1TB',
               unit_price: 1300,
            },
         ],
         description: 'iPhone 15 model description.',
         showcase_images: [
            {
               image_id: 'iphone-15-finish-select-202309-6-1inch-blue_zgxzmz',
               image_url:
                  'https://res.cloudinary.com/delkyrtji/image/upload/v1744960327/iphone-15-finish-select-202309-6-1inch-blue_zgxzmz.webp',
               image_name: 'iPhone 15 blue',
               image_description: '',
               image_width: 0,
               image_height: 0,
               image_bytes: 0,
               image_order: 0,
            },
            {
               image_id: 'iphone-15-finish-select-202309-6-1inch-pink_j6v96t',
               image_url:
                  'https://res.cloudinary.com/delkyrtji/image/upload/v1744960358/iphone-15-finish-select-202309-6-1inch-pink_j6v96t.webp',
               image_name: 'iPhone 15 pink',
               image_description: '',
               image_width: 0,
               image_height: 0,
               image_bytes: 0,
               image_order: 1,
            },
            {
               image_id: 'iphone-15-finish-select-202309-6-1inch-yellow_pwviwe',
               image_url:
                  'https://res.cloudinary.com/delkyrtji/image/upload/v1744960389/iphone-15-finish-select-202309-6-1inch-yellow_pwviwe.webp',
               image_name: 'iPhone 15 yellow',
               image_description: '',
               image_width: 0,
               image_height: 0,
               image_bytes: 0,
               image_order: 2,
            },
            {
               image_id: 'iphone-15-finish-select-202309-6-1inch-green_yk0ln5',
               image_url:
                  'https://res.cloudinary.com/delkyrtji/image/upload/v1744960447/iphone-15-finish-select-202309-6-1inch-green_yk0ln5.webp',
               image_name: 'iPhone 15 green',
               image_description: '',
               image_width: 0,
               image_height: 0,
               image_bytes: 0,
               image_order: 3,
            },
            {
               image_id: 'iphone-15-finish-select-202309-6-1inch-black_hhhvfs',
               image_url:
                  'https://res.cloudinary.com/delkyrtji/image/upload/v1744960469/iphone-15-finish-select-202309-6-1inch-black_hhhvfs.webp',
               image_name: 'iPhone 15 black',
               image_description: '',
               image_width: 0,
               image_height: 0,
               image_bytes: 0,
               image_order: 4,
            },
         ],
         overall_sold: 0,
         rating_stars: [
            {
               star: 1,
               count: 0,
            },
            {
               star: 2,
               count: 0,
            },
            {
               star: 3,
               count: 0,
            },
            {
               star: 4,
               count: 0,
            },
            {
               star: 5,
               count: 0,
            },
         ],
         average_rating: {
            rating_average_value: 0,
            rating_count: 0,
         },
         slug: 'iphone-15',
      },
   ],
   links: {
      first: '',
      prev: '',
      next: '',
      last: '',
   },
};
