// <auto-generated />
using System;
using GYZ.Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GYZ.Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountDbContext))]
    [Migration("20241127184615_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GYZ.Discount.Grpc.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DiscountValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxDiscountAmount")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinPurchaseAmount")
                        .HasColumnType("double precision");

                    b.Property<int>("QuantityRemain")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98a87729-5bcf-49f4-8a50-a4721dbf044d"),
                            Code = "CODE",
                            CreatedAt = new DateTime(2024, 11, 27, 18, 46, 15, 289, DateTimeKind.Utc).AddTicks(8032),
                            Description = "Summer 2024 description",
                            DiscountValue = 0.20000000000000001,
                            QuantityRemain = 20,
                            Status = 1,
                            Title = "Summer 2024",
                            Type = 0,
                            UpdatedAt = new DateTime(2024, 11, 27, 18, 46, 15, 289, DateTimeKind.Utc).AddTicks(8033),
                            UsageLimit = 20,
                            ValidFrom = new DateTime(2024, 11, 27, 18, 46, 15, 289, DateTimeKind.Utc).AddTicks(6032),
                            ValidTo = new DateTime(2024, 11, 27, 18, 46, 15, 289, DateTimeKind.Utc).AddTicks(6857)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
