services:
    nginx.webserver:
        image: nginx:stable
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - ./nginx.fe.conf:/etc/nginx/nginx.conf
        - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
        - client.web
        networks:
        - client-network
    
    client.web:
        image: baledev/client.web
        build:
            context: ./Client
            dockerfile: Dockerfile
        ports:
        - "3000:3000"
        networks:
        - client-network

    admin.web:
        image: baledev/admin.web
        build:
            context: ./Admin
            dockerfile: Dockerfile
        ports:
        - "4000:3000"
        networks:
        - client-network

networks:
  client-network:
    name: client-network
    driver: bridge





